'use client';
import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { ArrowRight, Check, Copy, Heart, Share2, Sparkles, Timer, Unlock } from 'lucide-react';
import { etsyBundleUrl, etsyListingUrl, shareUrl, vipCode } from '@/lib/config';
import { resets, ResetItem } from '@/src/data/resets';

export function Header(){const [vip,setVip]=useState(false);useEffect(()=>setVip(localStorage.getItem('vipUnlocked')==='true'),[]);return <header className="header"><Link className="brand" href="/">dias studio</Link><nav><Link href="/picker">Picker</Link><Link href="/task-unfreezer">Task Unfreezer</Link><Link href="/no-scroll">No-Scroll</Link><Link href="/printable">Printable</Link><Link href="/vip">VIP</Link></nav><a className="btn small" href={etsyListingUrl}>Get the Printable</a>{vip&&<span className="badge">VIP</span>}</header>}
export function Footer(){return <footer className="footer"><b>dias studio</b><p>© 2026 dias studio. All Rights Reserved.</p><div><Link href="/privacy">Privacy</Link><Link href="/terms">Terms</Link><Link href="/printable">Printable</Link><a href={etsyListingUrl}>Etsy</a><Link href="/share">Share this free picker</Link></div></footer>}
export function CTAButton({href,children,secondary}:{href:string;children:React.ReactNode;secondary?:boolean}){return <Link className={secondary?'btn secondary':'btn'} href={href}>{children}<ArrowRight size={16}/></Link>}
export function Badge({children}:{children:React.ReactNode}){return <span className="badge">{children}</span>}
export function DisclaimerBox(){return <section className="disclaimer">This tool is an ADHD-friendly organization and routine support tool. It is not medical, psychological, therapeutic, or diagnostic advice.</section>}
export function AppMockup(){return <div className="mockup"><div className="phone">scrolling<br/>bored<br/>stuck<br/>tired</div><div className="chips"><Badge>Low Energy</Badge><Badge>2 Minutes</Badge><Badge>Calm</Badge></div><div className="result-mini"><b>Your reset:</b><p>open a window + clear one item</p><small>60-page printable system</small></div></div>}
const energies=['low','medium','high','overloaded'] as const; const times=['2','5','15','30'] as const; const vibes=['calm','fun','movement','creative','social','home','focus','no-scroll'] as const;
function ChipGroup<T extends string>({label,items,value,set}:{label:string;items:readonly T[];value:T;set:(v:T)=>void}){return <fieldset className="chipgroup"><legend>{label}</legend>{items.map(i=><button type="button" key={i} className={value===i?'chip active':'chip'} onClick={()=>set(i)}>{i==='home'?'Home Reset':i==='focus'?'Focus Boost':i.replace('-', ' ')}</button>)}</fieldset>}
export function Picker({mini=false}:{mini?:boolean}){const [energy,setEnergy]=useState<(typeof energies)[number]>('low');const [time,setTime]=useState<(typeof times)[number]>('2');const [vibe,setVibe]=useState<(typeof vibes)[number]>('calm');const [result,setResult]=useState<ResetItem|null>(null);const [uses,setUses]=useState(0);function pick(){const vip=localStorage.getItem('vipUnlocked')==='true';const pool=resets.filter(r=>r.energy===energy&&r.time===time&&r.vibe===vibe&&(!r.vip||vip));const any=resets.filter(r=>r.energy===energy&&(!r.vip||vip));const chosen=(pool.length?pool:any)[Math.floor(Math.random()* (pool.length?pool:any).length)];setResult(chosen);const next=Number(localStorage.getItem('pickerUses')||'0')+1;localStorage.setItem('pickerUses',String(next));setUses(next)}return <div className="tool"><ChipGroup label="Energy" items={energies} value={energy} set={setEnergy}/><ChipGroup label="Time" items={times} value={time} set={setTime}/><ChipGroup label="Vibe" items={vibes} value={vibe} set={setVibe}/><button className="btn" onClick={pick}>Pick My Reset</button>{result&&<ResultCard item={result}/>} {(uses>=3||Number(typeof window!=='undefined'?localStorage.getItem('pickerUses')||0:0)>=3)&&<p className="soft-cta">Need more options? The printable system includes menus, cards, reward vaults, and task unfreezer pages.</p>}{mini&&<a className="textlink" href={etsyListingUrl}>Want the full printable system? Get the 60-page PDF on Etsy.</a>}</div>}
export function ResultCard({item}:{item:ResetItem}){return <article className="card result"><h3>{item.title}</h3><p>{item.action}</p><p><b>Start:</b> {item.startLine}</p><p><b>Reward:</b> {item.reward}</p><p><b>PDF match:</b> {item.pdfPage}</p><div className="row"><FavoriteButton item={item}/><TimerButton minutes={Number(item.time)}/><a className="btn small" href={etsyListingUrl}>Get the Printable on Etsy</a></div><ShareButtons compact/></article>}
export function FavoriteButton({item}:{item:ResetItem}){function save(){const list=JSON.parse(localStorage.getItem('favorites')||'[]'); if(!list.some((x:ResetItem)=>x.id===item.id)) list.push(item); localStorage.setItem('favorites',JSON.stringify(list)); localStorage.setItem('favoritesCount',String(list.length));}return <button className="btn secondary small" onClick={save}><Heart size={15}/>Save This Reset</button>}
export function TimerButton({minutes}:{minutes:number}){const [left,setLeft]=useState(minutes*60);const [on,setOn]=useState(false);useEffect(()=>{if(!on)return;const id=setInterval(()=>setLeft(l=>l>0?l-1:0),1000);return()=>clearInterval(id)},[on]);return <button className="btn secondary small" onClick={()=> left===0?(setLeft(minutes*60),setOn(false)):setOn(!on)}><Timer size={15}/>{on?'Pause':'Start Timer'} {Math.floor(left/60)}:{String(left%60).padStart(2,'0')}</button>}
export function ShareButtons({compact=false}:{compact?:boolean}){async function copy(){await navigator.clipboard?.writeText(shareUrl)}return <div className="share"><button className="btn secondary small" onClick={copy}><Copy size={15}/>Copy Share Link</button>{!compact&&<><a className="btn secondary small" href={`https://twitter.com/intent/tweet?url=${encodeURIComponent(shareUrl)}`}>X/Twitter</a><a className="btn secondary small" href={`https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(shareUrl)}`}>Facebook</a><a className="btn secondary small" href={`https://pinterest.com/pin/create/button/?url=${encodeURIComponent(shareUrl)}`}>Pinterest</a><a className="btn secondary small" href={`https://wa.me/?text=${encodeURIComponent(shareUrl)}`}>WhatsApp</a></>}</div>}
export function VIPUnlock(){const [code,setCode]=useState('');const [ok,setOk]=useState(false);const [err,setErr]=useState('');function unlock(){if(code.trim()===vipCode){localStorage.setItem('vipUnlocked','true');setOk(true);setErr('')}else setErr('That code did not match. Check the bonus access page inside your PDF.')}return <div className="tool"><label>Enter code<input value={code} onChange={e=>setCode(e.target.value)} /></label><button className="btn" onClick={unlock}><Unlock size={16}/>Unlock VIP Mode</button>{ok&&<p className="success">VIP mode unlocked: extra reset pool, reward vault suggestions, PDF page matching.</p>}{err&&<p className="error">{err}</p>}</div>}
export function ProductPreview(){return <div className="preview"><div>PDF cover placeholder</div><div>Printable page spread</div><div>Etsy listing preview</div></div>}
export function FeatureGrid({items}:{items:string[]}){return <div className="grid">{items.map(x=><div className="card" key={x}><Check size={18}/><h3>{x}</h3></div>)}</div>}
export function StepCards(){return <div className="grid three">{['Choose your energy|Low, medium, high, or overloaded.','Pick your time|2, 5, 15, or 30 minutes.','Get one tiny reset|A small action + reward idea + matching PDF page suggestion.'].map(s=>{const [a,b]=s.split('|');return <div className="card" key={a}><Sparkles/><h3>{a}</h3><p>{b}</p></div>})}</div>}
export {etsyListingUrl, etsyBundleUrl, shareUrl};
