import type {
  GenerationPayload,
  GenerationResult,
  OutputType,
  ProviderClient,
  ProviderName,
  QualityMode
} from '@/types/generation';

function escapeHtml(value: string): string {
  return value
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&#039;');
}

function qualityInstruction(qualityMode?: QualityMode): string {
  if (qualityMode === 'fast') return 'Fast mode with concise outputs.';
  if (qualityMode === 'beast') return 'Production mode with architecture-level details and implementation notes.';
  return 'Balanced mode with practical details.';
}

function buildInstruction(payload: GenerationPayload): string {
  return [
    'You are UltraGen AI Brain Orchestrator.',
    qualityInstruction(payload.qualityMode),
    `Language: ${payload.language}`,
    `Requested modules: ${payload.outputTypes.join(', ')}`,
    `User brief: ${payload.prompt}`,
    'Return a concise execution summary and specific deliverables.'
  ].join('\n');
}

function buildPreviewHtml(payload: GenerationPayload, provider: ProviderName): string {
  const safePrompt = escapeHtml(payload.prompt);
  const tags = payload.outputTypes
    .map(
      (type) =>
        `<span style="padding:4px 8px;border-radius:999px;background:#18232f;border:1px solid #334155">/${escapeHtml(type)}</span>`
    )
    .join(' ');

  const cards = payload.outputTypes
    .map((type) => {
      const blueprint = getOutputBlueprint(type);
      return `<article style="padding:12px;border:1px solid #1f2937;border-radius:12px;background:#050911">
        <h3 style="margin:0 0 8px;color:#67e8f9;font-size:14px">${escapeHtml(blueprint.title)}</h3>
        <p style="margin:0;color:#cbd5e1;font-size:13px">${escapeHtml(blueprint.previewHint)}</p>
      </article>`;
    })
    .join('');

  return `<!doctype html>
<html>
  <body style="margin:0;background:#020617;color:#e2e8f0;font-family:Inter,system-ui;padding:20px">
    <h2 style="margin-top:0">UltraGen AI Preview</h2>
    <p><strong>Provider:</strong> ${provider}</p>
    <p><strong>Prompt:</strong> ${safePrompt}</p>
    <div style="display:flex;flex-wrap:wrap;gap:8px">${tags}</div>
    <section style="margin-top:16px;display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:10px">${cards}</section>
  </body>
</html>`;
}

type OutputBlueprint = {
  title: string;
  previewHint: string;
  deliverables: string[];
  codeSnippet: string;
};

function getOutputBlueprint(output: OutputType): OutputBlueprint {
  if (output === 'web') {
    return {
      title: 'Web Builder',
      previewHint: 'React + Tailwind pages with responsive components and SEO wiring.',
      deliverables: ['Next.js app/web scaffold', 'UI sections + shared design tokens', 'Metadata, sitemap, robots'],
      codeSnippet: `// /web
export const webRoutes = ['/', '/pricing', '/dashboard'];`
    };
  }

  if (output === 'mobile') {
    return {
      title: 'Mobile Builder',
      previewHint: 'React Native/Flutter screen map with navigation and app state strategy.',
      deliverables: ['Screen flow map', 'Navigation + state structure', 'Android/iOS config checklist'],
      codeSnippet: `// /mobile
export const mobileFlow = ['Onboarding', 'Auth', 'Home', 'Settings'];`
    };
  }

  if (output === 'image') {
    return {
      title: 'Image Lab',
      previewHint: 'Flux / DALL·E prompt pack with art direction variants.',
      deliverables: ['Prompt library by style', 'Brand visual guide', 'Asset naming and versioning'],
      codeSnippet: `// /image
export const imageModels = ['flux.1', 'dall-e'];`
    };
  }

  return {
    title: 'Video Studio',
    previewHint: 'Luma / Runway storyboard with motion and voice-over beats.',
    deliverables: ['Scene timeline', 'Prompt + camera movement sheet', 'Audio/script draft'],
    codeSnippet: `// /video
export const videoModels = ['luma', 'runway'];`
  };
}

function buildCodeSample(payload: GenerationPayload, provider: ProviderName): string {
  const snippets = payload.outputTypes.map((output) => getOutputBlueprint(output).codeSnippet).join('\n\n');

  return `// Generated by UltraGen AI (${provider})
export const ultraGenPlan = {
  prompt: ${JSON.stringify(payload.prompt)},
  modules: ${JSON.stringify(payload.outputTypes)},
  quality: ${JSON.stringify(payload.qualityMode ?? 'balanced')}
};

${snippets}

export const deployChecklist = [
  'Validate outputs and secrets in /api/ai/generate',
  'Sync repository through GitHub API',
  'Trigger Vercel deployment and monitor build logs'
];`;
}

function buildFallbackSummary(provider: ProviderName, payload: GenerationPayload): string {
  return `[Demo mode] ${provider} key missing. Prepared architecture and delivery plan for modules: ${payload.outputTypes.join(', ')}.`;
}

function buildDeliverables(payload: GenerationPayload): string[] {
  return payload.outputTypes.flatMap((type) => {
    const blueprint = getOutputBlueprint(type);
    return blueprint.deliverables.map((item) => `${blueprint.title}: ${item}`);
  });
}

function buildMockResult(provider: ProviderName, payload: GenerationPayload): GenerationResult {
  return {
    id: crypto.randomUUID(),
    status: 'complete',
    summary: buildFallbackSummary(provider, payload),
    providerUsed: provider,
    deliverables: buildDeliverables(payload),
    previewHtml: buildPreviewHtml(payload, provider),
    codeSample: buildCodeSample(payload, provider)
  };
}

function normalizeOpenAiSummary(data: unknown): string | undefined {
  if (!data || typeof data !== 'object') return undefined;
  const parsed = data as Record<string, unknown>;
  if (typeof parsed.output_text === 'string' && parsed.output_text.trim().length > 0) return parsed.output_text;
  return undefined;
}

function normalizeAnthropicSummary(data: unknown): string | undefined {
  if (!data || typeof data !== 'object') return undefined;
  const parsed = data as Record<string, unknown>;
  if (!Array.isArray(parsed.content)) return undefined;
  const textNode = parsed.content.find((item) => {
    if (!item || typeof item !== 'object') return false;
    const node = item as Record<string, unknown>;
    return node.type === 'text' && typeof node.text === 'string';
  }) as Record<string, unknown> | undefined;

  return typeof textNode?.text === 'string' ? textNode.text : undefined;
}

async function callOpenAi(payload: GenerationPayload): Promise<GenerationResult> {
  const apiKey = process.env.OPENAI_API_KEY;
  if (!apiKey) return buildMockResult('openai', payload);

  const response = await fetch('https://api.openai.com/v1/responses', {
    method: 'POST',
    headers: { Authorization: `Bearer ${apiKey}`, 'Content-Type': 'application/json' },
    body: JSON.stringify({
      model: process.env.OPENAI_MODEL ?? 'gpt-4.1-mini',
      input: buildInstruction(payload),
      max_output_tokens: 350
    })
  });

  if (!response.ok) throw new Error(`OpenAI request failed (${response.status}): ${await response.text()}`);
  const summary = normalizeOpenAiSummary(await response.json()) ?? 'OpenAI generation completed.';
  return { ...buildMockResult('openai', payload), summary };
}

async function callAnthropic(payload: GenerationPayload): Promise<GenerationResult> {
  const apiKey = process.env.ANTHROPIC_API_KEY;
  if (!apiKey) return buildMockResult('anthropic', payload);

  const response = await fetch('https://api.anthropic.com/v1/messages', {
    method: 'POST',
    headers: {
      'x-api-key': apiKey,
      'anthropic-version': '2023-06-01',
      'Content-Type': 'application/json'
    },
    body: JSON.stringify({
      model: process.env.ANTHROPIC_MODEL ?? 'claude-3-5-haiku-latest',
      max_tokens: 350,
      messages: [{ role: 'user', content: buildInstruction(payload) }]
    })
  });

  if (!response.ok) throw new Error(`Anthropic request failed (${response.status}): ${await response.text()}`);
  const summary = normalizeAnthropicSummary(await response.json()) ?? 'Anthropic generation completed.';
  return { ...buildMockResult('anthropic', payload), summary };
}

async function callGemini(payload: GenerationPayload): Promise<GenerationResult> {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) return buildMockResult('gemini', payload);

  const model = process.env.GEMINI_MODEL ?? 'gemini-1.5-flash';
  const endpoint = `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${apiKey}`;
  const response = await fetch(endpoint, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ contents: [{ parts: [{ text: buildInstruction(payload) }] }] })
  });

  if (!response.ok) throw new Error(`Gemini request failed (${response.status}): ${await response.text()}`);
  return { ...buildMockResult('gemini', payload), summary: 'Gemini generation completed.' };
}

async function callGroq(payload: GenerationPayload): Promise<GenerationResult> {
  const apiKey = process.env.GROQ_API_KEY;
  if (!apiKey) return buildMockResult('groq', payload);

  const response = await fetch('https://api.groq.com/openai/v1/chat/completions', {
    method: 'POST',
    headers: { Authorization: `Bearer ${apiKey}`, 'Content-Type': 'application/json' },
    body: JSON.stringify({
      model: process.env.GROQ_MODEL ?? 'llama-3.3-70b-versatile',
      messages: [{ role: 'user', content: buildInstruction(payload) }],
      max_tokens: 350
    })
  });

  if (!response.ok) throw new Error(`Groq request failed (${response.status}): ${await response.text()}`);
  return { ...buildMockResult('groq', payload), summary: 'Groq generation completed.' };
}

function resolveProvider(provider?: string): ProviderName {
  if (provider === 'anthropic' || provider === 'gemini' || provider === 'groq') return provider;
  return 'openai';
}

function pickAutoProvider(payload: GenerationPayload): ProviderName {
  if (payload.outputTypes.includes('web')) return 'anthropic';
  if (payload.outputTypes.includes('mobile')) return 'openai';
  if (payload.outputTypes.includes('video')) return 'gemini';
  return 'openai';
}

export function getProviderClient(provider?: string): ProviderClient {
  return {
    async generate(payload) {
      const providerToUse = provider === 'auto' || !provider ? pickAutoProvider(payload) : resolveProvider(provider);
      if (providerToUse === 'anthropic') return callAnthropic(payload);
      if (providerToUse === 'gemini') return callGemini(payload);
      if (providerToUse === 'groq') return callGroq(payload);
      return callOpenAi(payload);
    }
  };
}
